<?php

return [
	'canada' => [
		'name' => 'Canada',
		'code' => 'CA',
		'type' => 'country',
		'bbox' => [
			'south' => 41.6765556,
			'west' => -141.00187,
			'north' => 83.1139,
			'east' => -52.6194,
		],
	],
	'alberta' => [
		'name' => 'Alberta',
		'code' => 'AB',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 48.99731,
			'west' => -120.0,
			'north' => 60.0,
			'east' => -109.98,
		],
		'children' => [
			'alberta_south_west' => [
				'name' => 'Alberta South West',
				'code' => 'AB-SW',
				'type' => 'tile',
				'parent' => 'alberta',
				'bbox' => [
					'south' => 48.99731,
					'west' => -120.0,
					'north' => 54.5,
					'east' => -115.0,
				],
			],
			'alberta_south_east' => [
				'name' => 'Alberta South East',
				'code' => 'AB-SE',
				'type' => 'tile',
				'parent' => 'alberta',
				'bbox' => [
					'south' => 48.99731,
					'west' => -115.0,
					'north' => 54.5,
					'east' => -109.98,
				],
			],
			'alberta_north_west' => [
				'name' => 'Alberta North West',
				'code' => 'AB-NW',
				'type' => 'tile',
				'parent' => 'alberta',
				'bbox' => [
					'south' => 54.5,
					'west' => -120.0,
					'north' => 60.0,
					'east' => -115.0,
				],
			],
			'alberta_north_east' => [
				'name' => 'Alberta North East',
				'code' => 'AB-NE',
				'type' => 'tile',
				'parent' => 'alberta',
				'bbox' => [
					'south' => 54.5,
					'west' => -115.0,
					'north' => 60.0,
					'east' => -109.98,
				],
			],
		],
	],
	'british_columbia' => [
		'name' => 'British Columbia',
		'code' => 'BC',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 48.30261,
			'west' => -139.06,
			'north' => 60.0,
			'east' => -114.03,
		],
		'children' => [
			'british_columbia_south_west' => [
				'name' => 'British Columbia South West',
				'code' => 'BC-SW',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 48.30261,
					'west' => -139.06,
					'north' => 52.0,
					'east' => -129.0,
				],
			],
			'british_columbia_south_central' => [
				'name' => 'British Columbia South Central',
				'code' => 'BC-SC',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 48.30261,
					'west' => -129.0,
					'north' => 52.0,
					'east' => -121.0,
				],
			],
			'british_columbia_south_east' => [
				'name' => 'British Columbia South East',
				'code' => 'BC-SE',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 48.30261,
					'west' => -121.0,
					'north' => 52.0,
					'east' => -114.03,
				],
			],
			'british_columbia_north_west' => [
				'name' => 'British Columbia North West',
				'code' => 'BC-NW',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 52.0,
					'west' => -139.06,
					'north' => 60.0,
					'east' => -129.0,
				],
			],
			'british_columbia_north_central' => [
				'name' => 'British Columbia North Central',
				'code' => 'BC-NC',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 52.0,
					'west' => -129.0,
					'north' => 60.0,
					'east' => -121.0,
				],
			],
			'british_columbia_north_east' => [
				'name' => 'British Columbia North East',
				'code' => 'BC-NE',
				'type' => 'tile',
				'parent' => 'british_columbia',
				'bbox' => [
					'south' => 52.0,
					'west' => -121.0,
					'north' => 60.0,
					'east' => -114.03,
				],
			],
		],
	],
	'manitoba' => [
		'name' => 'Manitoba',
		'code' => 'MB',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 48.99886,
			'west' => -102.0,
			'north' => 60.0,
			'east' => -88.97,
		],
		'children' => [
			'manitoba_south_west' => [
				'name' => 'Manitoba South West',
				'code' => 'MB-SW',
				'type' => 'tile',
				'parent' => 'manitoba',
				'bbox' => [
					'south' => 48.99886,
					'west' => -102.0,
					'north' => 54.5,
					'east' => -95.5,
				],
			],
			'manitoba_south_east' => [
				'name' => 'Manitoba South East',
				'code' => 'MB-SE',
				'type' => 'tile',
				'parent' => 'manitoba',
				'bbox' => [
					'south' => 48.99886,
					'west' => -95.5,
					'north' => 54.5,
					'east' => -88.97,
				],
			],
			'manitoba_north_west' => [
				'name' => 'Manitoba North West',
				'code' => 'MB-NW',
				'type' => 'tile',
				'parent' => 'manitoba',
				'bbox' => [
					'south' => 54.5,
					'west' => -102.0,
					'north' => 60.0,
					'east' => -95.5,
				],
			],
			'manitoba_north_east' => [
				'name' => 'Manitoba North East',
				'code' => 'MB-NE',
				'type' => 'tile',
				'parent' => 'manitoba',
				'bbox' => [
					'south' => 54.5,
					'west' => -95.5,
					'north' => 60.0,
					'east' => -88.97,
				],
			],
		],
	],
	'new_brunswick' => [
		'name' => 'New Brunswick',
		'code' => 'NB',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 44.55964,
			'west' => -69.05,
			'north' => 47.31,
			'east' => -63.67,
		],
	],
	'newfoundland_and_labrador' => [
		'name' => 'Newfoundland and Labrador',
		'code' => 'NL',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 46.51,
			'west' => -67.82,
			'north' => 60.37,
			'east' => -52.62,
		],
		'children' => [
			'labrador_west' => [
				'name' => 'Labrador West',
				'code' => 'NL-LW',
				'type' => 'tile',
				'parent' => 'newfoundland_and_labrador',
				'bbox' => [
					'south' => 51.0,
					'west' => -67.82,
					'north' => 60.37,
					'east' => -60.5,
				],
			],
			'labrador_east' => [
				'name' => 'Labrador East',
				'code' => 'NL-LE',
				'type' => 'tile',
				'parent' => 'newfoundland_and_labrador',
				'bbox' => [
					'south' => 51.0,
					'west' => -60.5,
					'north' => 60.37,
					'east' => -52.62,
				],
			],
			'newfoundland_island' => [
				'name' => 'Newfoundland Island',
				'code' => 'NL-NI',
				'type' => 'tile',
				'parent' => 'newfoundland_and_labrador',
				'bbox' => [
					'south' => 46.51,
					'west' => -59.5,
					'north' => 51.9,
					'east' => -52.62,
				],
			],
		],
	],
	'northwest_territories' => [
		'name' => 'Northwest Territories',
		'code' => 'NT',
		'type' => 'territory',
		'parent' => 'canada',
		'bbox' => [
			'south' => 60.0,
			'west' => -136.46,
			'north' => 78.87,
			'east' => -102.0,
		],
		'children' => [
			'northwest_territories_south_west' => [
				'name' => 'Northwest Territories South West',
				'code' => 'NT-SW',
				'type' => 'tile',
				'parent' => 'northwest_territories',
				'bbox' => [
					'south' => 60.0,
					'west' => -136.46,
					'north' => 67.5,
					'east' => -119.0,
				],
			],
			'northwest_territories_south_east' => [
				'name' => 'Northwest Territories South East',
				'code' => 'NT-SE',
				'type' => 'tile',
				'parent' => 'northwest_territories',
				'bbox' => [
					'south' => 60.0,
					'west' => -119.0,
					'north' => 67.5,
					'east' => -102.0,
				],
			],
			'northwest_territories_north_west' => [
				'name' => 'Northwest Territories North West',
				'code' => 'NT-NW',
				'type' => 'tile',
				'parent' => 'northwest_territories',
				'bbox' => [
					'south' => 67.5,
					'west' => -136.46,
					'north' => 78.87,
					'east' => -119.0,
				],
			],
			'northwest_territories_north_east' => [
				'name' => 'Northwest Territories North East',
				'code' => 'NT-NE',
				'type' => 'tile',
				'parent' => 'northwest_territories',
				'bbox' => [
					'south' => 67.5,
					'west' => -119.0,
					'north' => 78.87,
					'east' => -102.0,
				],
			],
		],
	],
	'nova_scotia' => [
		'name' => 'Nova Scotia',
		'code' => 'NS',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 43.42,
			'west' => -66.45,
			'north' => 47.03,
			'east' => -59.73,
		],
	],
	'nunavut' => [
		'name' => 'Nunavut',
		'code' => 'NU',
		'type' => 'territory',
		'parent' => 'canada',
		'bbox' => [
			'south' => 51.62,
			'west' => -102.0,
			'north' => 83.1139,
			'east' => -61.05,
		],
		'children' => [
			'nunavut_south_west' => [
				'name' => 'Nunavut South West',
				'code' => 'NU-SW',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 51.62,
					'west' => -102.0,
					'north' => 62.0,
					'east' => -88.0,
				],
			],
			'nunavut_south_central' => [
				'name' => 'Nunavut South Central',
				'code' => 'NU-SC',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 51.62,
					'west' => -88.0,
					'north' => 62.0,
					'east' => -74.0,
				],
			],
			'nunavut_south_east' => [
				'name' => 'Nunavut South East',
				'code' => 'NU-SE',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 51.62,
					'west' => -74.0,
					'north' => 62.0,
					'east' => -61.05,
				],
			],
			'nunavut_north_west' => [
				'name' => 'Nunavut North West',
				'code' => 'NU-NW',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 62.0,
					'west' => -102.0,
					'north' => 83.1139,
					'east' => -85.0,
				],
			],
			'nunavut_north_central' => [
				'name' => 'Nunavut North Central',
				'code' => 'NU-NC',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 62.0,
					'west' => -85.0,
					'north' => 83.1139,
					'east' => -73.0,
				],
			],
			'nunavut_north_east' => [
				'name' => 'Nunavut North East',
				'code' => 'NU-NE',
				'type' => 'tile',
				'parent' => 'nunavut',
				'bbox' => [
					'south' => 62.0,
					'west' => -73.0,
					'north' => 83.1139,
					'east' => -61.05,
				],
			],
		],
	],
	'ontario' => [
		'name' => 'Ontario',
		'code' => 'ON',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 41.6765556,
			'west' => -95.16,
			'north' => 56.86,
			'east' => -74.34,
		],
		'children' => [
			'ontario_south_west' => [
				'name' => 'Ontario South West',
				'code' => 'ON-SW',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 41.6765556,
					'west' => -95.16,
					'north' => 46.5,
					'east' => -89.5,
				],
			],
			'ontario_south_central_west' => [
				'name' => 'Ontario South Central West',
				'code' => 'ON-SCW',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 41.6765556,
					'west' => -89.5,
					'north' => 46.5,
					'east' => -84.5,
				],
			],
			'ontario_south_central_east' => [
				'name' => 'Ontario South Central East',
				'code' => 'ON-SCE',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 41.6765556,
					'west' => -84.5,
					'north' => 46.5,
					'east' => -79.5,
				],
			],
			'ontario_south_east' => [
				'name' => 'Ontario South East',
				'code' => 'ON-SE',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 41.6765556,
					'west' => -79.5,
					'north' => 46.5,
					'east' => -74.34,
				],
			],
			'ontario_central_west' => [
				'name' => 'Ontario Central West',
				'code' => 'ON-CW',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 46.5,
					'west' => -95.16,
					'north' => 50.5,
					'east' => -88.0,
				],
			],
			'ontario_central' => [
				'name' => 'Ontario Central',
				'code' => 'ON-C',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 46.5,
					'west' => -88.0,
					'north' => 50.5,
					'east' => -81.0,
				],
			],
			'ontario_central_east' => [
				'name' => 'Ontario Central East',
				'code' => 'ON-CE',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 46.5,
					'west' => -81.0,
					'north' => 50.5,
					'east' => -74.34,
				],
			],
			'ontario_north_west' => [
				'name' => 'Ontario North West',
				'code' => 'ON-NW',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 50.5,
					'west' => -95.16,
					'north' => 56.86,
					'east' => -84.5,
				],
			],
			'ontario_north_east' => [
				'name' => 'Ontario North East',
				'code' => 'ON-NE',
				'type' => 'tile',
				'parent' => 'ontario',
				'bbox' => [
					'south' => 50.5,
					'west' => -84.5,
					'north' => 56.86,
					'east' => -74.34,
				],
			],
		],
	],
	'prince_edward_island' => [
		'name' => 'Prince Edward Island',
		'code' => 'PE',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 45.95,
			'west' => -64.43,
			'north' => 47.08,
			'east' => -61.97,
		],
	],
	'quebec' => [
		'name' => 'Quebec',
		'code' => 'QC',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 44.99,
			'west' => -79.77,
			'north' => 62.59,
			'east' => -57.1,
		],
		'children' => [
			'quebec_south_west' => [
				'name' => 'Quebec South West',
				'code' => 'QC-SW',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 44.99,
					'west' => -79.77,
					'north' => 50.0,
					'east' => -71.5,
				],
			],
			'quebec_south_central' => [
				'name' => 'Quebec South Central',
				'code' => 'QC-SC',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 44.99,
					'west' => -71.5,
					'north' => 50.0,
					'east' => -64.5,
				],
			],
			'quebec_south_east' => [
				'name' => 'Quebec South East',
				'code' => 'QC-SE',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 44.99,
					'west' => -64.5,
					'north' => 50.0,
					'east' => -57.1,
				],
			],
			'quebec_north_west' => [
				'name' => 'Quebec North West',
				'code' => 'QC-NW',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 50.0,
					'west' => -79.77,
					'north' => 62.59,
					'east' => -70.0,
				],
			],
			'quebec_north_central' => [
				'name' => 'Quebec North Central',
				'code' => 'QC-NC',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 50.0,
					'west' => -70.0,
					'north' => 62.59,
					'east' => -63.0,
				],
			],
			'quebec_north_east' => [
				'name' => 'Quebec North East',
				'code' => 'QC-NE',
				'type' => 'tile',
				'parent' => 'quebec',
				'bbox' => [
					'south' => 50.0,
					'west' => -63.0,
					'north' => 62.59,
					'east' => -57.1,
				],
			],
		],
	],
	'saskatchewan' => [
		'name' => 'Saskatchewan',
		'code' => 'SK',
		'type' => 'province',
		'parent' => 'canada',
		'bbox' => [
			'south' => 49.0,
			'west' => -110.0,
			'north' => 60.0,
			'east' => -101.36,
		],
	],
	'yukon' => [
		'name' => 'Yukon',
		'code' => 'YT',
		'type' => 'territory',
		'parent' => 'canada',
		'bbox' => [
			'south' => 60.0,
			'west' => -141.00187,
			'north' => 69.65,
			'east' => -123.8,
		],
	],
];
